# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 176)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.label.setObjectName("label")
        self.lbTentativa = QtWidgets.QLabel(self.centralwidget)
        self.lbTentativa.setGeometry(QtCore.QRect(90, 20, 67, 17))
        self.lbTentativa.setText("")
        self.lbTentativa.setObjectName("lbTentativa")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 51, 17))
        self.label_2.setObjectName("label_2")
        self.lbNome = QtWidgets.QLabel(self.centralwidget)
        self.lbNome.setGeometry(QtCore.QRect(60, 70, 67, 17))
        self.lbNome.setText("")
        self.lbNome.setObjectName("lbNome")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.label_3.setObjectName("label_3")
        self.lbUsuario = QtWidgets.QLabel(self.centralwidget)
        self.lbUsuario.setGeometry(QtCore.QRect(70, 100, 121, 17))
        self.lbUsuario.setText("")
        self.lbUsuario.setObjectName("lbUsuario")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 51, 17))
        self.label_4.setObjectName("label_4")
        self.lbPonto = QtWidgets.QLabel(self.centralwidget)
        self.lbPonto.setGeometry(QtCore.QRect(70, 130, 67, 17))
        self.lbPonto.setText("")
        self.lbPonto.setObjectName("lbPonto")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 10, 131, 17))
        self.label_5.setObjectName("label_5")
        self.varNumero = QtWidgets.QLineEdit(self.centralwidget)
        self.varNumero.setGeometry(QtCore.QRect(300, 30, 113, 25))
        self.varNumero.setObjectName("varNumero")
        self.btEnvair = QtWidgets.QPushButton(self.centralwidget)
        self.btEnvair.setGeometry(QtCore.QRect(430, 30, 89, 25))
        self.btEnvair.setObjectName("btEnvair")
        self.lbResposta = QtWidgets.QLabel(self.centralwidget)
        self.lbResposta.setGeometry(QtCore.QRect(270, 110, 241, 17))
        self.lbResposta.setText("")
        self.lbResposta.setObjectName("lbResposta")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 90, 81, 17))
        self.label_6.setObjectName("label_6")
        self.btJogaNovamente = QtWidgets.QPushButton(self.centralwidget)
        self.btJogaNovamente.setGeometry(QtCore.QRect(398, 140, 141, 25))
        self.btJogaNovamente.setObjectName("btJogaNovamente")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "jogo"))
        self.label.setText(_translate("MainWindow", "tentativas:"))
        self.label_2.setText(_translate("MainWindow", "nome:"))
        self.label_3.setText(_translate("MainWindow", "usuário:"))
        self.label_4.setText(_translate("MainWindow", "pontos:"))
        self.label_5.setText(_translate("MainWindow", "insira um nomero:"))
        self.varNumero.setInputMask(_translate("MainWindow", "###########"))
        self.btEnvair.setText(_translate("MainWindow", "enviar"))
        self.label_6.setText(_translate("MainWindow", "resposta:"))
        self.btJogaNovamente.setText(_translate("MainWindow", "jogar novamente"))
