# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(246, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btCriar = QtWidgets.QPushButton(self.centralwidget)
        self.btCriar.setStyleSheet("background-color: rgb(51, 209, 122);")
        self.btCriar.setObjectName("btCriar")
        self.gridLayout.addWidget(self.btCriar, 9, 0, 1, 1)
        self.varUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.varUsuario.setObjectName("varUsuario")
        self.gridLayout.addWidget(self.varUsuario, 3, 0, 1, 1)
        self.btLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btLimpar.setStyleSheet("background-color: rgb(237, 51, 59);")
        self.btLimpar.setObjectName("btLimpar")
        self.gridLayout.addWidget(self.btLimpar, 10, 0, 1, 1)
        self.varSenhaNV = QtWidgets.QLineEdit(self.centralwidget)
        self.varSenhaNV.setObjectName("varSenhaNV")
        self.gridLayout.addWidget(self.varSenhaNV, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.varSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.varSenha.setObjectName("varSenha")
        self.gridLayout.addWidget(self.varSenha, 5, 0, 1, 1)
        self.varNme = QtWidgets.QLineEdit(self.centralwidget)
        self.varNme.setObjectName("varNme")
        self.gridLayout.addWidget(self.varNme, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.btEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.btEntrar.setStyleSheet("background-color: rgb(98, 160, 234);")
        self.btEntrar.setObjectName("btEntrar")
        self.gridLayout.addWidget(self.btEntrar, 11, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "cadastro"))
        self.btCriar.setText(_translate("MainWindow", "criar"))
        self.btLimpar.setText(_translate("MainWindow", "limpar"))
        self.label.setText(_translate("MainWindow", "nome:"))
        self.label_4.setText(_translate("MainWindow", "insira a senha novamente:"))
        self.label_2.setText(_translate("MainWindow", "usuário:"))
        self.label_3.setText(_translate("MainWindow", "senha:"))
        self.btEntrar.setText(_translate("MainWindow", "entrar"))
