# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(184, 151)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.varUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.varUsuario.setObjectName("varUsuario")
        self.gridLayout.addWidget(self.varUsuario, 1, 0, 1, 2)
        self.varSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.varSenha.setObjectName("varSenha")
        self.gridLayout.addWidget(self.varSenha, 3, 0, 1, 2)
        self.lbLogin = QtWidgets.QLabel(self.centralwidget)
        self.lbLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.lbLogin.setObjectName("lbLogin")
        self.gridLayout.addWidget(self.lbLogin, 0, 0, 1, 1)
        self.lbSenha = QtWidgets.QLabel(self.centralwidget)
        self.lbSenha.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSenha.setObjectName("lbSenha")
        self.gridLayout.addWidget(self.lbSenha, 2, 0, 1, 1)
        self.btEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.btEntrar.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.btEntrar.setObjectName("btEntrar")
        self.gridLayout.addWidget(self.btEntrar, 7, 1, 1, 1)
        self.btCadastro = QtWidgets.QPushButton(self.centralwidget)
        self.btCadastro.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.btCadastro.setObjectName("btCadastro")
        self.gridLayout.addWidget(self.btCadastro, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lbLogin.setText(_translate("MainWindow", "usuario:"))
        self.lbSenha.setText(_translate("MainWindow", "senha:"))
        self.btEntrar.setText(_translate("MainWindow", "entrar"))
        self.btCadastro.setText(_translate("MainWindow", "cadastrar"))
